# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  terraform {
    required_version = ">= 0.14"
    required_providers {
      azurerm = {
        source  = "hashicorp/aws"
        version = ">= 4.22.0"
        }
      }
    }
